### ISSUE TITLE
Java Error ?

### ISSUE THREAD

**Issue by TrialMacameau** [skogaby/butterfly#1]
C:\Users\TrialMacameau\Desktop>java -Ddb_path="C:\Users\TrialMacameau\Desktop\DDR_Profile\db.sqlite" -jar butterfly-1.0.0.jar
[INFO ] 2019-06-18 10:58:18.838 [main] KotlinDetector - Kotlin reflection implementation not found at runtime, related features won't be available.
[INFO ] 2019-06-18 10:58:19.452 [main] Version - HHH000412: Hibernate Core {[WORKING]}
[INFO ] 2019-06-18 10:58:19.454 [main] Environment - HHH000205: Loaded properties from resource hibernate.properties: {jdbc.username=, hibernate.dialect=com.buttongames.butterflydao.hibernate.SQLiteDialect, hibernate.show_sql=false, hibernate.bytecode.use_reflection_optimizer=false, jdbc.password=, hibernate.hbm2ddl.auto=update, jdbc.driverClassName=org.sqlite.JDBC}
[INFO ] 2019-06-18 10:58:19.627 [main] Version - HCANN000001: Hibernate Commons Annotations {5.1.0.Final}
[INFO ] 2019-06-18 10:58:19.994 [main] Dialect - HHH000400: Using dialect: com.buttongames.butterflydao.hibernate.SQLiteDialect
[INFO ] 2019-06-18 10:58:20.022 [main] LobCreatorBuilderImpl - HHH000423: Disabling contextual LOB creation as JDBC driver reported JDBC version [2] less than 4
[INFO ] 2019-06-18 10:58:20.748 [main] JtaPlatformInitiator - HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
[Thread-1] INFO org.eclipse.jetty.util.log - Logging initialized @2631ms to org.eclipse.jetty.util.log.Slf4jLog
[Thread-1] INFO spark.embeddedserver.jetty.EmbeddedJettyServer - == Spark has ignited ...
[Thread-1] INFO spark.embeddedserver.jetty.EmbeddedJettyServer - >> Listening on 0.0.0.0:80
[Thread-1] INFO org.eclipse.jetty.server.Server - jetty-9.4.z-SNAPSHOT, build timestamp: 2017-11-21T16:27:37-05:00, git hash: 82b8fb23f757335bb3329d540ce37a2a2615f0a8
[Thread-1] INFO org.eclipse.jetty.server.session - DefaultSessionIdManager workerName=node0
[Thread-1] INFO org.eclipse.jetty.server.session - No SessionScavenger set, using defaults
[Thread-1] INFO org.eclipse.jetty.server.session - Scavenging every 600000ms
[Thread-1] INFO org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@5d3d26{HTTP/1.1,[http/1.1]}{0.0.0.0:80}
[Thread-1] INFO org.eclipse.jetty.server.Server - Started @2707ms

A friend of mine says there's a Java error and I tried to switch the service link to the one that's lisening but to no avail

**Comment by skogaby** [comment]
Resolving this issue... it doesn't provide any actual error output or useful log info and it's a few months old.
